package CACIE.ui;
import java.awt.*;import java.util.*;import javax.sound.midi.Sequencer;import javax.swing.*;import CACIE.eventlist.*;import CACIE.genome.Motif_simpleTree_Individual;

/** Four instrument lanes, one shared timeline and one continuously running Sequence. */
public final class MultiLaneBreedingPanel extends JPanel {
 public static final int SLOT_COUNT=8,LANE_COUNT=4;private static final int[] CHANNELS={0,1,2,3};
 private static final String[] TONICS={"C","C#","D","Eb","E","F","F#","G","Ab","A","Bb","B"};
 private final JComboBox<BreedingPanel.PlaybackLength>[] lengths=new JComboBox[SLOT_COUNT];private final Lane[] lanes=new Lane[LANE_COUNT];private final JProgressBar[] progress=new JProgressBar[SLOT_COUNT];
 private final JButton play=new JButton("Play sequence"),drum=new JButton("PlayWithDrumBeat"),loop=new JButton("Loop Sequence"),loopDrum=new JButton("Loop With Drum Beat"),stop=new JButton("Stop");private final JLabel status=new JLabel(" ");
 private javax.swing.Timer timer;private Sequencer sequencer;private PlaybackSequencePlan plan;private RealtimeLoopSequence realtime;private boolean looping,withDrums,updating;private long committed=-1,revision;private int playingSlot=-1,tempo=CommonEventList.DT;
 private final class Lane {final int index;final JComboBox<String> instrument=new JComboBox<String>(GMInstruments.labels());final Motif_simpleTree_Individual[] source=new Motif_simpleTree_Individual[SLOT_COUNT];final CommonEventList[] events=new CommonEventList[SLOT_COUNT];final JComboBox<String>[] tonic=new JComboBox[SLOT_COUNT];final JComboBox<ScaleType>[] scale=new JComboBox[SLOT_COUNT];final BreedingIndividualSlot[] slot=new BreedingIndividualSlot[SLOT_COUNT];final JPanel[] card=new JPanel[SLOT_COUNT];Lane(int i){index=i;instrument.setSelectedIndex(i==0?0:i==1?32:i==2?48:56);instrument.addActionListener(e->{if(!updating)queueUpdate();});}}
 public MultiLaneBreedingPanel(java.util.List<Motif_simpleTree_Individual> initial){setLayout(new BorderLayout(0,4));setBorder(BorderFactory.createEmptyBorder(5,7,5,7));setBackground(new Color(239,242,246));add(header(),BorderLayout.NORTH);JPanel body=new JPanel();body.setOpaque(false);body.setLayout(new BoxLayout(body,BoxLayout.Y_AXIS));body.add(lengthRow());for(int i=0;i<LANE_COUNT;i++){lanes[i]=new Lane(i);body.add(laneRow(lanes[i]));}add(body,BorderLayout.CENTER);if(initial!=null)for(int i=0;i<Math.min(8,initial.size());i++)setRaw(0,i,initial.get(i));refreshEnabled();}
 private JPanel header(){JPanel p=new JPanel(new BorderLayout());p.setOpaque(false);JLabel t=new JLabel("Playback - four synchronized instrument lanes");t.setFont(t.getFont().deriveFont(Font.BOLD,16f));p.add(t,BorderLayout.WEST);JPanel c=new JPanel(new FlowLayout(FlowLayout.RIGHT,3,0));c.setOpaque(false);play.addActionListener(e->play(false));drum.addActionListener(e->play(true));loop.addActionListener(e->playLoop(false));loopDrum.addActionListener(e->playLoop(true));stop.addActionListener(e->stopPlayback());stop.setEnabled(false);for(JButton b:new JButton[]{play,drum,loop,loopDrum,stop})c.add(b);c.add(status);p.add(c,BorderLayout.EAST);return p;}
 private JPanel lengthRow(){JPanel o=new JPanel(new BorderLayout(4,0));o.setOpaque(false);o.setBorder(BorderFactory.createTitledBorder("Shared Length timeline"));JLabel l=new JLabel("All instruments",SwingConstants.CENTER);l.setPreferredSize(new Dimension(145,42));o.add(l,BorderLayout.WEST);JPanel g=new JPanel(new GridLayout(1,8,4,0));g.setOpaque(false);for(int i=0;i<8;i++){final int s=i;JPanel cell=new JPanel(new BorderLayout());cell.setOpaque(false);lengths[i]=new JComboBox<BreedingPanel.PlaybackLength>(BreedingPanel.PlaybackLength.values());lengths[i].setSelectedItem(BreedingPanel.PlaybackLength.FOUR_BEATS);lengths[i].addActionListener(e->lengthChanged(s));cell.add(lengths[i]);progress[i]=new JProgressBar(0,1000);progress[i].setPreferredSize(new Dimension(60,4));progress[i].setBorderPainted(false);progress[i].setForeground(new Color(255,178,36));cell.add(progress[i],BorderLayout.SOUTH);g.add(cell);}o.add(g);return o;}
 private JPanel laneRow(Lane l){JPanel o=new JPanel(new BorderLayout(4,0));o.setOpaque(false);o.setBorder(BorderFactory.createTitledBorder("Instrument Lane "+(l.index+1)+"  /  MIDI channel "+(CHANNELS[l.index]+1)));JPanel h=new JPanel(new BorderLayout());h.setOpaque(false);h.setPreferredSize(new Dimension(145,140));h.add(new JLabel("GM Instrument"),BorderLayout.NORTH);h.add(l.instrument);o.add(h,BorderLayout.WEST);JPanel g=new JPanel(new GridLayout(1,8,4,0));g.setOpaque(false);for(int i=0;i<8;i++){final int s=i;JPanel col=new JPanel();col.setOpaque(false);col.setLayout(new BoxLayout(col,BoxLayout.Y_AXIS));l.tonic[i]=new JComboBox<String>(TONICS);l.scale[i]=new JComboBox<ScaleType>(ScaleType.values());l.scale[i].setSelectedItem(ScaleType.DIATONIC);l.tonic[i].addActionListener(e->settingChanged(l,s));l.scale[i].addActionListener(e->settingChanged(l,s));col.add(l.tonic[i]);col.add(l.scale[i]);l.card[i]=new JPanel(new BorderLayout());l.card[i].setPreferredSize(new Dimension(96,96));l.card[i].setMaximumSize(new Dimension(Integer.MAX_VALUE,96));l.slot[i]=new BreedingIndividualSlot(BreedingIndividualSlot.SlotType.PLAYBACK,s,true);l.slot[i].setImportListener((target,individual)->dropped(l.index,s,individual));l.card[i].add(l.slot[i]);col.add(l.card[i]);g.add(col);}o.add(g);return o;}
 private void dropped(int lane,int slot,Motif_simpleTree_Individual individual){if(!looping)stopPlayback();setRaw(lane,slot,individual);queueUpdate();}
 private void setRaw(int lane,int slot,Motif_simpleTree_Individual individual){Lane l=lanes[lane];l.source[slot]=individual==null?null:(Motif_simpleTree_Individual)individual.clone();rebuild(l,slot);refreshEnabled();}
 private void lengthChanged(int slot){if(updating)return;for(Lane l:lanes)if(l!=null)rebuild(l,slot);queueUpdate();}private void settingChanged(Lane l,int slot){if(updating)return;rebuild(l,slot);queueUpdate();}
 private void rebuild(Lane l,int s){Motif_simpleTree_Individual source=l.source[s];if(source==null){l.events[s]=null;l.slot[s].setIndividual(null);return;}long ticks=getPlaybackTicks(s);PlaybackSettings settings=new PlaybackSettings(ticks==Long.MAX_VALUE?Double.POSITIVE_INFINITY:ticks/16.0,ScaleFilter.tonicFromName((String)l.tonic[s].getSelectedItem()),(ScaleType)l.scale[s].getSelectedItem());l.events[s]=source.createPlaybackClone(settings).convertToEventList();l.slot[s].setIndividual(source);l.slot[s].setText(null);l.slot[s].setIcon(TreeQuiltIcon.create(source,l.events[s]));l.slot[s].setToolTipText("Lane "+(l.index+1)+", slot "+(s+1)+" - "+l.events[s].getNumOfNotes()+" notes");}
 public void setIndividual(int lane,int slot,Motif_simpleTree_Individual individual,PlaybackSettings settings){if(!looping)stopPlayback();Lane l=lanes[lane];updating=true;long tick=Double.isInfinite(settings.getBeats())?Long.MAX_VALUE:Math.round(settings.getBeats()*16);for(BreedingPanel.PlaybackLength v:BreedingPanel.PlaybackLength.values())if(v.getTicks()==tick)lengths[slot].setSelectedItem(v);l.tonic[slot].setSelectedItem(ScaleFilter.tonicName(settings.getTonic()));l.scale[slot].setSelectedItem(settings.getScale());updating=false;setRaw(lane,slot,individual);queueUpdate();}
 private PlaybackSequencePlan build(boolean drums)throws Exception{ArrayList<PlaybackLaneData> data=new ArrayList<PlaybackLaneData>();for(Lane l:lanes)data.add(new PlaybackLaneData(Arrays.asList(l.events),CHANNELS[l.index],l.instrument.getSelectedIndex()));ArrayList<Long> shared=new ArrayList<Long>();for(int i=0;i<8;i++)shared.add(getPlaybackTicks(i));return PlaybackSequenceBuilder.buildLanes(data,shared,tempo,drums);}
 private void play(boolean drums){stopPlayback();try{plan=build(drums);if(plan.getSegments().isEmpty()){finish();return;}sequencer=plan.getMIDISequence().playMIDISequenceWithSequencer();transport(false);stop.setEnabled(true);timer=new javax.swing.Timer(33,e->animate());timer.start();}catch(Exception e){e.printStackTrace();stopPlayback();}}
 private void playLoop(boolean drums){stopPlayback();try{PlaybackSequencePlan first=build(drums);if(first.getSegments().isEmpty()){finish();return;}realtime=new RealtimeLoopSequence(tempo);realtime.append(0,first);realtime.append(1,first);realtime.append(2,first);sequencer=realtime.getMIDISequence().playMIDISequenceWithSequencer();plan=first;looping=true;withDrums=drums;committed=-1;revision=0;status.setText("Loop 1");transport(false);stop.setEnabled(true);timer=new javax.swing.Timer(33,e->animate());timer.start();}catch(Exception e){e.printStackTrace();stopPlayback();}}
 private void queueUpdate(){if(!looping||sequencer==null||realtime==null)return;long r=++revision;try{long tick=sequencer.getTickPosition();RealtimeLoopSequence.Block current=at(tick);if(current==null)return;long target=current.loopNumber+1;PlaybackSequencePlan next=build(withDrums);if(number(target)==null)realtime.append(target,next);RealtimeLoopSequence.Block replaced=realtime.replaceFuture(target,next,tick);if(number(target+1)==null)realtime.append(target+1,next);status.setText("Pending: Loop "+(replaced.loopNumber+1)+"  r"+r);}catch(IllegalStateException late){SwingUtilities.invokeLater(this::queueUpdate);}catch(Exception e){e.printStackTrace();}}
 private void animate(){if(sequencer==null||plan==null)return;long absolute=sequencer.getTickPosition(),local=absolute;if(looping){RealtimeLoopSequence.Block b=at(absolute);if(b!=null){plan=b.plan;local=absolute-b.startTick;PlaybackSequencePlan.Segment last=last(plan);if(last!=null&&local>=last.startTick&&committed<b.loopNumber)commit(b);}}PlaybackSequencePlan.Segment active=plan.segmentAt(local);playingSlot=active==null?-1:active.slot;for(int i=0;i<8;i++){int v=0;for(PlaybackSequencePlan.Segment s:plan.getSegments())if(s.slot==i){v=local>=s.endTick?1000:local<s.startTick?0:(int)Math.round(s.progress(local)*1000);break;}progress[i].setValue(v);}borders();if(!looping&&!sequencer.isRunning()&&absolute>=plan.getTotalTicks())finish();}
 private void commit(RealtimeLoopSequence.Block current){committed=current.loopNumber;try{PlaybackSequencePlan next=build(withDrums);long target=current.loopNumber+1;realtime.replaceFuture(target,next,sequencer.getTickPosition());if(number(target+2)==null)realtime.append(target+2,next);status.setText("Next: Loop "+(target+1)+"  r"+revision);}catch(Exception e){e.printStackTrace();}}
 private PlaybackSequencePlan.Segment last(PlaybackSequencePlan p){java.util.List<PlaybackSequencePlan.Segment> s=p.getSegments();return s.isEmpty()?null:s.get(s.size()-1);}private RealtimeLoopSequence.Block at(long tick){for(RealtimeLoopSequence.Block b:realtime.getBlocks())if(tick>=b.startTick&&tick<b.endTick)return b;return null;}private RealtimeLoopSequence.Block number(long n){for(RealtimeLoopSequence.Block b:realtime.getBlocks())if(b.loopNumber==n)return b;return null;}
 public void stopPlayback(){if(timer!=null){timer.stop();timer=null;}if(sequencer!=null){if(sequencer.isRunning())sequencer.stop();sequencer.close();sequencer=null;}plan=null;realtime=null;looping=false;finish();}private void finish(){playingSlot=-1;status.setText(" ");borders();for(JProgressBar p:progress)if(p!=null)p.setValue(0);refreshEnabled();stop.setEnabled(false);}private void refreshEnabled(){boolean any=false;for(Lane l:lanes)if(l!=null)for(CommonEventList e:l.events)if(e!=null)any=true;if(!looping)transport(any);}private void transport(boolean on){play.setEnabled(on);drum.setEnabled(on);loop.setEnabled(on);loopDrum.setEnabled(on);}private void borders(){for(Lane l:lanes)if(l!=null)for(int i=0;i<8;i++)l.card[i].setBorder(BorderFactory.createLineBorder(i==playingSlot?new Color(255,178,36):new Color(56,82,108),i==playingSlot?4:2));}
 public long getPlaybackTicks(int slot){return ((BreedingPanel.PlaybackLength)lengths[slot].getSelectedItem()).getTicks();}public void setTempo(int t){if(t<=0)throw new IllegalArgumentException("Tempo must be positive");tempo=t;}public boolean isLooping(){return looping&&sequencer!=null&&sequencer.isOpen();}
}
